// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllConfigDB() {
  return window['go']['main']['App']['AllConfigDB']();
}

export function DeleteAllConfig() {
  return window['go']['main']['App']['DeleteAllConfig']();
}

export function DeleteConfigDB(arg1) {
  return window['go']['main']['App']['DeleteConfigDB'](arg1);
}

export function GetAllTable(arg1) {
  return window['go']['main']['App']['GetAllTable'](arg1);
}

export function GetColumnTable(arg1, arg2) {
  return window['go']['main']['App']['GetColumnTable'](arg1, arg2);
}

export function GetTypeColumn(arg1, arg2) {
  return window['go']['main']['App']['GetTypeColumn'](arg1, arg2);
}

export function GetValuesTable(arg1, arg2) {
  return window['go']['main']['App']['GetValuesTable'](arg1, arg2);
}

export function InsertRow(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertRow'](arg1, arg2, arg3);
}

export function SaveTemplateToFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTemplateToFile'](arg1, arg2, arg3);
}

export function TestConnectDB(arg1, arg2) {
  return window['go']['main']['App']['TestConnectDB'](arg1, arg2);
}
