// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AllConfigDB():Promise<Array<main.DatabaseConfig>>;

export function DeleteAllConfig():Promise<boolean>;

export function DeleteConfigDB(arg1:number):Promise<boolean>;

export function GetAllTable(arg1:number):Promise<Array<string>>;

export function GetColumnTable(arg1:string,arg2:number):Promise<Array<string>>;

export function GetValuesTable(arg1:string,arg2:number):Promise<Array<{[key: string]: any}>>;

export function SaveTemplateToFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TestConnectDB(arg1:string,arg2:main.DatabaseType):Promise<boolean>;
